---
language: python
python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

env:
  global:
    ROLE_NAME: nextcloud

install:
  - pip install molecule docker

  - ansible --version

  - pwd

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - cd ../
  - mv ansible-role-$ROLE_NAME nkakouros-original.$ROLE_NAME
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
