---

- name: Extract download file type
  set_fact:
    download_file_type: "{{ nextcloud_download_url[-4:] }}"

- name: Install unzip
  package:
    name: unzip
    state: present
  when: download_file_type == '.zip'

- name: Remove trailing slash from installation directory
  set_fact:
    nextcloud_installation_dir: >-
      {{ nextcloud_installation_dir | regex_replace('/$', '') }}

- name: Read installation parent dir
  set_fact:
    nextcloud_installation_parent_dir: "{{ nextcloud_installation_dir | dirname }}"

- name: Download nextcloud releases list
  get_url:
    url: https://github.com/nextcloud/server/releases.atom
    dest: /tmp/

- name: Check if update is available
  block:
    - template:
        src: check_updates.sh.j2
        dest: /tmp/check_updates.sh
        mode: 0700
      changed_when: false
    - command: /tmp/check_updates.sh
      register: update_status
      changed_when: false

- name: Download nextcloud
  unarchive:
    src: "{{ nextcloud_download_url }}"
    dest: "{{ nextcloud_installation_parent_dir }}"
    remote_src: yes
    owner: "{{ nextcloud_file_owner }}"
    group: "{{ nextcloud_file_owner }}"
  when: update_status.stdout == "UPDATE_AVAILABLE"

- name: Move nextcloud folder
  command: mv "{{ nextcloud_installation_parent_dir }}" "{{ nextcloud_installation_dir }}"
  when:
    - update_status.stdout == "UPDATE_AVAILABLE"
    - nextcloud_installation_dir | basename != "nextcloud"

- name: Install nextcloud
  command: >-
    php occ maintenance:install --no-interaction
      --database "{{ nextcloud_db_backend }}"
      --database-name "{{ nextcloud_db_name }}"
      --database-user "{{ nextcloud_db_user }}"
      --database-pass "{{ nextcloud_db_pass }}"
      --database-host "{{ nextcloud_db_host }}"
      --database-port "{{ nextcloud_db_port }}"
      --admin-user "{{ nextcloud_admin_user }}"
      --admin-pass "{{ nextcloud_admin_pass }}"
      --data-dir "{{ nextcloud_data_dir }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
    creates: "{{ nextcloud_installation_dir }}/config/config.php"
  become_user: "{{ nextcloud_file_owner }}"

- name: Set file permissions
  block:
    - find:
        # We are doing the next 4 task instead of only one or two to have correct change detection
        path: "{{ nextcloud_installation_dir }}"
        file_type: any
      register: nextcloud_installation_files
    - file:
        path: "{{ item.path }}"
        owner: "{{ nextcloud_file_owner }}"
        group: "{{ nextcloud_file_owner }}"
        mode: "u=rwX,g=rX,o-rwx"
        state: directory
        recurse: yes
      with_items: "{{ nextcloud_installation_files.files | selectattr('isdir') | list }}"
    - file:
        path: "{{ item.path }}"
        owner: "{{ nextcloud_file_owner }}"
        group: "{{ nextcloud_file_owner }}"
        mode: "u=rw,g=r,o-rwx"
      with_items: "{{ nextcloud_installation_files.files | selectattr('isdir', 'equalto', 'false') | list }}"
      when: item.path != '.htaccess'
    - file:
        path: "{{ nextcloud_installation_dir }}"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0750
        state: directory
    - file:
        path: "{{ nextcloud_installation_dir }}/occ"
        mode: "u+x"
    - file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0644
