---

- name: Read extra files
  block:
    - command: "php occ integrity:check-core --output=json"
      args:
        chdir: "{{ nextcloud_installation_dir }}"
      register: nextcloud_integrity_core
      become_user: "{{ nextcloud_file_owner }}"
      failed_when: false
      changed_when: false

    - command: "php occ integrity:check-app {{ item }} --output=json"
      args:
        chdir: "{{ nextcloud_installation_dir }}"
      register: nextcloud_integrity_apps
      loop: >-
        {{
          (
            nextcloud_installed_apps.enabled
            | combine(nextcloud_installed_apps.disabled)
          ).keys()
          | list
        }}
      changed_when: false
      failed_when: false
      become_user: "{{ nextcloud_file_owner }}"

    - set_fact:
        nextcloud_extra_files: >-
          [
            {%- for result in nextcloud_integrity_apps.results -%}
              {%- set appname=(result.cmd[3]) -%}
              {%- set files=(result.stdout_lines[-1] | from_json) -%}
              {%- if files is mapping and 'EXTRA_FILE' in files -%}
                "{{ []
                  | zip_longest(
                    files['EXTRA_FILE'].keys(),
                    fillvalue=("apps/" ~ appname)
                  )
                  | map('join', '/')
                  | list
                  | join('","') }}"
                  ,
              {%- endif -%}
            {%- endfor -%}
            {%- set files=(
                  nextcloud_integrity_core.stdout_lines[-1]
                  | from_json
                )
            -%}
            {%- if files is mapping and 'EXTRA_FILE' in files -%}
              '{{ files["EXTRA_FILE"].keys() | join("','") }}'
            {%- endif -%}
          ]

# Using `command` instead of `file` with a loop to make it (much) faster.
- name: Delete extra files
  command: rm -f "{{ nextcloud_extra_files | join(' ') }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
    warn: false
  when: nextcloud_extra_files | length > 0
