---

- include_tasks: assertions.yml

- include_tasks: install.yml

- include_tasks: setup.yml

- import_tasks: apps.yml

- include_tasks: cleanup.yml

- include_tasks: user.yml

- include_tasks: user_config.yml
