---

- name: Check if upgrade is needed
  command: php occ status
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: nextcloud_status
  changed_when: false
  become_user: "{{ nextcloud_file_owner }}"

- name: Upgrade Nextcloud installation
  command: php occ upgrade
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become_user: "{{ nextcloud_file_owner }}"
  when: >-
    nextcloud_status.stdout
      | search('Nextcloud or one of the apps require upgrade')
