---

- name: Create users
  command: >-
    php occ user:add
      "{{ item.name }}"
      --display-name "{{ item.display_name }}"
      --password-from-env
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become_user: "{{ nextcloud_file_owner }}"
  environment:
    OC_PASS: "{{ item.pass }}"
  with_items: "{{ nextcloud_users }}"
