---

- name: Update .htaccess
  block:
    - name: Make .htaccess writable
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g+w
      listen: nextcloud update htaccess
    - name: Update .htaccess file
      command: ./occ maintenance:update:htaccess --no-interaction
      args:
        chdir: "{{ nextcloud_installation_dir }}"
      listen: nextcloud update htaccess
      become: true
      become_user: "{{ nextcloud_file_owner }}"
    - name: Make .htaccess unwritable again
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g-w
      listen: nextcloud update htaccess

- name: Set permissions on downloaded apps
  file:
    path: "{{ nextcloud_installation_dir }}/apps/"
    mode: u=rwX,g=rX,o=rX
    owner: "{{ nextcloud_file_owner }}"
    group: "{{ nextcloud_file_owner }}"
    state: directory
    recurse: true
  listen: set app files permissions
