---

- name: Update .htaccess
  block:
    - file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g+w
      listen: nextcloud update htaccess
    - command: php occ maintenance:update:htaccess --no-interaction
      args:
        chdir: "{{ nextcloud_installation_dir }}"
      listen: nextcloud update htaccess
      become_user: "{{ nextcloud_file_owner }}"
    - file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g-w
      listen: nextcloud update htaccess

- name: Set permissions on downloaded apps
  file:
    path: "{{ nextcloud_installation_dir }}/apps/"
    mode: u=rwX,g=rX,o=rX
    owner: "{{ nextcloud_file_owner }}"
    group: "{{ nextcloud_file_owner }}"
    state: directory
    recurse: yes
  listen: set app files permissions

- name: Upgrade Nextcloud installation
  command: php occ upgrade
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become_user: "{{ nextcloud_file_owner }}"
  listen: run occ upgrade
