---

- name: Update .htaccess
  command: php occ maintenance:update:htaccess --no-interaction
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become_method: sudo
  become_user: "{{ nextcloud_file_owner }}"
  listen: nextcloud update htaccess
