---

- name: Install unzip
  package:
    name: unzip
    state: present
  when: download_file_type == '.zip'

- name: Install imagemagick
  package:
    name: imagemagick

- name: Upload script to check for updates
  template:
    src: check_updates.sh.j2
    dest: /tmp/check_updates.sh
    mode: 0o700
  changed_when: false

- name: Check if update is available
  command: /tmp/check_updates.sh
  register: update_status
  changed_when: false

- name: Download nextcloud
  unarchive:
    src: "{{ nextcloud_download_url }}"
    dest: "{{ nextcloud_installation_parent_dir }}"
    remote_src: true
    owner: "{{ nextcloud_file_owner }}"
    group: "{{ nextcloud_file_owner }}"
  when: update_status.stdout == "UPDATE_AVAILABLE"

# When extracting the downloaded nextcloud archive, the files are placed under
# a nextcloud folder. Here, we rename this folder if the user has specified a
# different folder.
- name: Move nextcloud folder
  command: >-
    mv
      "{{ nextcloud_installation_parent_dir }}/nextcloud"
      "{{ nextcloud_installation_dir }}"
  when:
    - update_status.stdout == "UPDATE_AVAILABLE"
    - nextcloud_installation_dir | basename != "nextcloud"

- name: Install nextcloud
  command: >-
    php occ maintenance:install --no-interaction
      --database "{{ nextcloud_database.backend }}"
      --database-name "{{ nextcloud_database.name }}"
      --database-user "{{ nextcloud_database.user }}"
      --database-pass "{{ nextcloud_database.pass }}"
      --database-host "{{ nextcloud_database.host }}"
      --database-port "{{ nextcloud_database.port }}"
      --admin-user "{{ nextcloud_admin_user }}"
      --admin-pass "{{ nextcloud_admin_pass }}"
      --data-dir "{{ nextcloud_data_dir }}"
  args:
    chdir: "{{ nextcloud_installation_dir }}"
    creates: "{{ nextcloud_installation_dir }}/config/config.php"
  become: true
  become_user: "{{ nextcloud_file_owner }}"

- name: Find Nextcloud files
  find:
    path: "{{ nextcloud_installation_dir }}"
    file_type: any
  register: nextcloud_installation_files

- name: Set file permissions on Nextcloud files
  block:
    - name: Set permissions on directories
      file:
        path: "{{ item.path }}"
        owner: "{{ nextcloud_file_owner }}"
        group: "{{ nextcloud_file_owner }}"
        mode: "u=rwX,g=rX,o-rwx"
        state: directory
        recurse: true
      loop:
        "{{ nextcloud_installation_files.files | selectattr('isdir') | list }}"
    # For files, we are using `shell` as `file` with a loop would take ages to
    # complete.
    - name: Set ownership on files
      command: >-
        find "{{ nextcloud_installation_dir }}"
          -type f
          ! -name '.htaccess'
          -exec
            chown {{ nextcloud_file_owner }}:{{ nextcloud_file_owner }} {} \;
      changed_when: false
    - name: Set permissions on files
      command: >-
        find "{{ nextcloud_installation_dir }}"
          -type f
          ! -name '.htaccess'
          ! -name 'occ'
          -exec chmod 0640 {} \;
      changed_when: false
    - name: Set permissions on installation directory
      file:
        path: "{{ nextcloud_installation_dir }}"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0o750
        state: directory
    - name: Make occ executable
      file:
        path: "{{ nextcloud_installation_dir }}/occ"
        mode: "u+x"
    - name: Set permissions on htaccess file
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0o644
