---

- name: Check if upgrade is needed
  command: ./occ status
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  register: nextcloud_status
  changed_when: false
  become: true
  become_user: "{{ nextcloud_file_owner }}"

- name: Upgrade Nextcloud installation
  command: ./occ upgrade
  args:
    chdir: "{{ nextcloud_installation_dir }}"
  become: true
  become_user: "{{ nextcloud_file_owner }}"
  when: >-
    nextcloud_status.stdout
      is search('Nextcloud or one of the apps require upgrade')
