---

- name: Prepare
  hosts: all
  become: true
  vars:
    mysql_root_password_update: false
    mysql_databases:
      - name: nextcloud
    mysql_users:
      - name: nextcloud
        password: password
        priv: "nextcloud.*:ALL"
    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb
    php_packages_extra:
      - libapache2-mod-php7.0
      - php-zip
      - php-imap
      - php-gd
      - php-json
      - php-xml
      - php-mbstring
      - php-mysql
      - php-curl
      - php-bz2
      - php-intl
      - php-mcrypt
      - php-gmp
      - php-apcu
      - php-imagick
      - php-curl
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: cloud.kakouros.net
        documentroot: /var/www/html/nextcloud
        extra_parameters: |
          SetEnv HOME /var/www/html/nextcloud
          SetEnv HTTP_HOME /var/www/html/nextcloud
    apache_mods_enabled:
      - rewrite.load
      - php7.0.load
      - headers.load
      - env.load
      - dir.load
      - mime.load
    apache_state: restarted
    manala_cron_files:
      - file: nextcloud
        user: www-data
        jobs:
          - name: Run nextcloud cron
            job: "php-cli -f {{ apache_vhosts.0.documentroot }}/cron.php"
            minute: "*/1"
  pre_tasks:
    - name: Gather facts
      setup: null
      become: false
  tasks:
    - include_role:
        name: geerlingguy.php
    - include_role:
        name: geerlingguy.apache
    - include_role:
        name: geerlingguy.mysql
    - include_role:
        name: geerlingguy.cron
